streamclient/streamclient.go, streamclient/streamclient_test.go
We were trying to use the streamclient.NewConsumerAndProducer helper and in the optoins function set the `kc.ConsumerConfig.Consumer.Offsets.Initial = sarama.OffsetNewest`, which failed because in this flow the ConsumerConfig was never initialised and still _nil_.
This change initialises the both the ConsumerConfig and the ProducerConfig on the kafka.Client.
=> Fix a nil pointer error

Gopkg.lock, Gopkg.toml
Reverts blendle/go-streamprocessor#54
Reverting this to unblock all the other PRs (removes merge conflicts).
=> Revert "Update sarama to 1.16.0"

stream/client.go, stream/client_test.go, stream/consumer.go, stream/consumer_test.go, stream/message.go, stream/message_test.go, stream/producer.go, stream/producer_test.go
This is a work-in-progress. I'm going to create several PRs, all based off of each other. I'll be working on this on-and-off again in my evening hours as a fun project, but feel free to block some time to review the PRs, as I think it's important we do this right, before we start using this in many more processors in the future.
---
This adds the initial interfaces, mostly as they where before, with some slight changes. Most significantly, the consumers and producers now take their own (optional) configuration values, instead of inheriting them from the client.
I've also removed some of the client implementation-specific values from the `Message` struct. We'll tackle that later.
=> Add initial stream package

script/test, script/tests/go-test-bench, script/tests/gometalinter, streamclient/standardstreamclient/client.go, streamclient/standardstreamclient/client_test.go, streamclient/standardstreamclient/consumer.go, streamclient/standardstreamclient/consumer_test.go, streamclient/standardstreamclient/producer.go, streamclient/standardstreamclient/producer_test.go, streamconfig/standardstreamconfig/consumer.go, streamconfig/standardstreamconfig/consumer_test.go, streamconfig/standardstreamconfig/producer.go, streamconfig/standardstreamconfig/producer_test.go
This is a work-in-progress. I'm going to create several PRs, all based off of each other. I'll be working on this on-and-off again in my evening hours as a fun project, but feel free to block some time to review the PRs, as I think it's important we do this right, before we start using this in many more processors in the future.
---
This adds the initial `standardstreamclient` implementation.
Still to do:
- document in README
- more unit testing
- benchmark tests (not really relevant for this client, but a good way to create the framework for future benchmark tests)
- cucumber tests (re-usable for other client implementations following in subsequent PRs)
=> Initial standardstreamclient implementation

streamclient/consumer.go, streamclient/consumer_test.go, streamclient/producer.go, streamclient/producer_test.go, streamconfig/initializers.go, streamconfig/initializers_test.go
These functions are the main entrypoint into the functionality of this
package.
It is fairly straight forward:
In the case of NewConsumer, if you set the `STREAMCLIENT_CONSUMER`
environment variable to the name of one of the streamclient
implementations, it will return that implementation. Valid names are:
- standardstream
- inmem
- kafka
- pubsub*
If you _don't_ pass in the environment variable, but send data to the
application over Stdin, the "standardstream" consumer will be returned
from this function:
echo '{"hello": "world" }' | go run main.go
In the case of NewProducer, the same applies as the consumer, except
that the environment variable is named `STREAMCLIENT_PRODUCER`.
Also, there is no concept of Stdin for the producer, but if you set
the environment variable `DRY_RUN` to …
=>  Add standardstream.NewConsumer/Producer functions

streamclient/inmemclient/consumer.go, streamclient/inmemclient/producer.go, streamclient/kafkaclient/consumer.go, streamclient/kafkaclient/producer.go, streamclient/standardstreamclient/consumer.go, streamclient/standardstreamclient/producer.go, streamconfig/config.go, streamconfig/config_test.go
=> Readability & usability improvements

streamconfig/config.go, streamconfig/config_test.go, streamconfig/initializers.go, streamconfig/initializers_test.go, streamconfig/inmemconfig/consumer.go, streamconfig/inmemconfig/producer.go, streamconfig/kafkaconfig/consumer.go, streamconfig/kafkaconfig/options.go, streamconfig/kafkaconfig/producer.go, streamconfig/kafkaconfig/producer_test.go, streamconfig/standardstreamconfig/consumer.go, streamconfig/standardstreamconfig/producer.go, streamconfig/testing.go, streamconfig/testing_test.go
So, I was all jacked-up, ready to hit the ground running and take this bad boy for a spin...
... and then I realised there's no way to actually configure your stream client of choice _outside_ of the code-base 😱 
I thought about rolling my own, but then remembered I saw Kelsey Hightower give a presentation once where he showed one of his Go packages, which did exactly what I needed. So I chose that one instead, and it works great:
https://github.com/kelseyhightower/envconfig
Couple of additions in this PR:
Here's an example of the current configuration values:
```
This application is configured via the environment. The following environment
variables can be used:
KEY                                     TYPE                              DEFAULT    REQUIRED    DESCRIPTION …
```
=> Allow configuring stream clients using environment variables

Gopkg.lock, Gopkg.toml, streamclient/kafkaclient/producer.go, streamconfig/config_test.go, streamconfig/initializers.go, streamconfig/kafkaconfig/options.go, streamconfig/kafkaconfig/producer.go, streamconfig/kafkaconfig/producer_test.go
@jurriaan sent me a link to http://blog.yaorenjie.com/2017/01/03/Kafka-0-10-Compression-Benchmark/, so I wanted to do some testing with LZ4 compression.
This PR makes the compression codec configurable.
=> Add support for configurable message compression

streamclient/consumer_test.go, streamclient/inmemclient/consumer.go, streamclient/inmemclient/consumer_test.go, streamclient/inmemclient/producer.go, streamclient/inmemclient/producer_test.go, streamclient/kafkaclient/consumer.go, streamclient/kafkaclient/consumer_test.go, streamclient/kafkaclient/producer.go, streamclient/kafkaclient/producer_test.go, streamclient/kafkaclient/testing.go, streamclient/kafkaclient/testing_test.go, streamclient/producer_test.go, streamclient/standardstreamclient/consumer.go, streamclient/standardstreamclient/producer.go, streamclient/testing.go, streamclient/testing_test.go, streamconfig/config.go, streamconfig/kafkaconfig/testing.go, streamutils/testutils/testing.go
Some tweaks and fixes, continuing working through some TODO's before releasing the next version.
=> Moar tweaks and fixes

stream/consumer.go, stream/consumermock.go, stream/producer.go, stream/producermock.go, streamclient/inmemclient/consumer.go, streamclient/inmemclient/consumer_test.go, streamclient/inmemclient/producer.go, streamclient/inmemclient/producer_test.go, streamclient/kafkaclient/consumer.go, streamclient/kafkaclient/consumer_test.go, streamclient/kafkaclient/eventhandlers.go, streamclient/kafkaclient/producer.go, streamclient/kafkaclient/producer_test.go, streamclient/standardstreamclient/consumer.go, streamclient/standardstreamclient/consumer_test.go, streamclient/standardstreamclient/producer.go, streamclient/standardstreamclient/producer_test.go, streamclient/standardstreamclient/testing.go, streamconfig/config.go, streamconfig/testing.go, streamcore/error.go, streamcore/error_test.go
Every producer and consumer now has its own internal errors channel to
which any errors are delivered that occur during consuming or producing
messages from or to the stream.
By default, this errors channel is consumed internally, and any error
received on the channel is logged on a "fatal" level, indicating the
message is sent to stderr, and the application exits with status code 1.
This default behavior can be changed, by setting the `HandleErrors`
configuration flag to false, indicating that the consumer or producer
should not listen to the errors channel. When configured like this, the
processor application itself is required to listen to any errors being
sent to the `Errors()` channel, and the processor should dictate what to
do with each error.
For now, the errors are delivered in …
=> Introduce `Errors()` channel for consumers and producers

streamclient/inmemclient/consumer.go, streamclient/inmemclient/producer.go, streamclient/kafkaclient/consumer.go, streamclient/kafkaclient/producer.go, streamclient/standardstreamclient/consumer.go, streamclient/standardstreamclient/producer.go, streamcore/interrupt.go, streamcore/interrupt_test.go
=> Improve Interrupt signal handling + testing

script/test, script/tests/go-test, script/tests/go-test-bench, script/tests/go-test-cover, script/tests/go-test-race, script/tests/godog, script/tests/gometalinter, streamclient/inmemclient/consumer_test.go, streamclient/kafkaclient/consumer.go, streamclient/kafkaclient/consumer_test.go, streamclient/kafkaclient/eventhandlers.go, streamclient/kafkaclient/testing.go, streamclient/kafkaclient/testing_test.go, streamclient/standardstreamclient/consumer.go, streamclient/standardstreamclient/consumer_test.go, streamclient/standardstreamclient/producer.go, streamclient/testing.go, streamclient/testing_test.go, streamconfig/config.go, streamconfig/kafkaconfig/types_test.go, streamutils/testutils/testing_test.go
=> Minor improvements to some tests & code

stream/consumer.go, stream/consumermock.go, stream/message.go, stream/message_test.go, stream/producer.go, stream/producermock.go, stream/testing.go, stream/testing_test.go, streamclient/inmemclient/consumer.go, streamclient/inmemclient/consumer_test.go, streamclient/inmemclient/producer.go, streamclient/inmemclient/producer_test.go, streamclient/inmemclient/testing_test.go, streamclient/kafkaclient/consumer.go, streamclient/kafkaclient/consumer_test.go, streamclient/kafkaclient/eventhandlers.go, streamclient/kafkaclient/producer.go, streamclient/kafkaclient/producer_test.go, streamclient/kafkaclient/testing.go, streamclient/kafkaclient/testing_test.go, streamclient/standardstreamclient/consumer.go, streamclient/standardstreamclient/consumer_test.go, streamclient/standardstreamclient/producer.go, streamclient/standardstreamclient/producer_test.go, streamclient/standardstreamclient/testing_test.go, streamclient/testing.go, streamclient/testing_test.go, streamutils/inmemstore/store.go, streamutils/inmemstore/store_test.go
This makes it easier to use the Message struct, and it keeps the same
message package name as version 1 of the library.
To prevent a circular import cycle, the `Config()` function now returns
an interface that can be cast to either a `streamconfig.Consumer` or
`streamconfig.Producer` struct.
This is an acceptable trade-off, as you really only use this function
sparsely (and probably only in test scenarios), whereas you use the
`Message` struct constantly.
=> Move streammsg.Message to stream.Message

.gitignore, .travis.yml, script/tests/gometalinter, streamclient/inmemclient/consumer.go, streamclient/inmemclient/producer.go, streamclient/kafkaclient/consumer.go, streamclient/kafkaclient/producer.go, streamclient/kafkaclient/testing.go, streamclient/kafkaclient/testing_test.go, streamclient/standardstreamclient/consumer.go, streamclient/standardstreamclient/producer.go, streamconfig/config.go, streamconfig/config_test.go, streamconfig/initializers.go, streamconfig/initializers_test.go, streamconfig/testing.go, streamconfig/testing_test.go
This allows us to manipulate the functionality of the logger on runtime,
such as changing the log-level via a unix signal.
=> Change logger to be a pointer to zap.Logger

streamclient/consumer_test.go, streamclient/inmemclient/consumer.go, streamclient/inmemclient/consumer_test.go, streamclient/inmemclient/producer.go, streamclient/inmemclient/producer_test.go, streamclient/inmemclient/testing_test.go, streamclient/kafkaclient/consumer.go, streamclient/kafkaclient/consumer_test.go, streamclient/kafkaclient/eventhandlers.go, streamclient/kafkaclient/producer.go, streamclient/kafkaclient/producer_test.go, streamclient/kafkaclient/testing_test.go, streamclient/producer_test.go, streamclient/standardstreamclient/consumer.go, streamclient/standardstreamclient/consumer_test.go, streamclient/standardstreamclient/producer.go, streamclient/standardstreamclient/producer_test.go, streamclient/standardstreamclient/testing_test.go
There's no need, so let's clean up our public API.
=> Don't export Consumer/Producer client structs

streamclient/consumer.go, streamclient/consumer_test.go, streamclient/inmemclient/consumer.go, streamclient/inmemclient/consumer_test.go, streamclient/inmemclient/producer.go, streamclient/inmemclient/producer_test.go, streamclient/inmemclient/testing.go, streamclient/inmemclient/testing_test.go, streamclient/kafkaclient/consumer.go, streamclient/kafkaclient/consumer_test.go, streamclient/kafkaclient/producer.go, streamclient/kafkaclient/producer_test.go, streamclient/kafkaclient/testing.go, streamclient/kafkaclient/testing_test.go, streamclient/producer.go, streamclient/producer_test.go, streamclient/standardstreamclient/consumer.go, streamclient/standardstreamclient/consumer_test.go, streamclient/standardstreamclient/producer.go, streamclient/standardstreamclient/producer_test.go, streamclient/standardstreamclient/testing.go, streamclient/testing_test.go, streamconfig/config.go, streamconfig/config_test.go, streamconfig/initializers.go, streamconfig/initializers_test.go, streamconfig/option.go, streamconfig/option_test.go, streamconfig/testing.go, streamconfig/testing_test.go
I was kind of annoyed at the (useless) verbosity of the configuration API
when configuring a new consumer and/or producer. Especially since 90% of
the stream processors are configured through environment variables
anyway, and only a few have to set elaborate lists of configuration
values in the code.
Right now, it's not uncommon to see the following lines in all
processors:
```golang
consumerOpts := func(c *streamconfig.Consumer) {
c.Logger = *logger.L
}
consumer, err := streamclient.NewConsumer(consumerOpts)
// handle error
producerOpts := func(c *streamconfig.Producer) {
c.Logger = *logger.L
}
producer, err := streamclient.NewProducer(producerOpts)
// handle error
```
Like I said, there's a lot of useless verbosity there.
Now, it becomes much simpler/cleaner to do this:
```golang
log := …
```
=> Implement new configuration API

streamclient/inmemclient/consumer.go, streamclient/inmemclient/producer.go, streamclient/kafkaclient/consumer.go, streamclient/kafkaclient/producer.go, streamclient/standardstreamclient/consumer.go, streamclient/standardstreamclient/producer.go, streamutil/interrupt.go, streamutil/interrupt_test.go
While not _directly_ related to streams or stream processors, interrupt
handling is a _very_ important aspect of stream processing, as you want as
much control over when you stop your processor as possible.
This is why this library has had correct "default" interrupt behavior
from the start (essentially cleanly closing any open consumers or
producers when required).
However, cleanly closing a producer or consumer is not always enough, as
your business logic is very much a driving factor in dictating what the
"correct" behavior is when an interrupt or kill signal is received.
For example, if your business logic reaches out into data stores other
than the streams you are consuming from or producing to, you might want to
wait for those actions to be finished cleanly, before stopping your …
=> Add `streamutil.Interrupt()` function

streamclient/kafkaclient/consumer_test.go, streamclient/kafkaclient/eventhandlers.go, streamconfig/config_test.go, streamconfig/kafkaconfig/consumer.go, streamconfig/kafkaconfig/consumer_test.go, streamconfig/kafkaconfig/testing.go, streamconfig/kafkaconfig/testing_test.go, streamconfig/option.go, streamconfig/option_test.go
This allows you to set an `OffsetDefault` for kafka. There are two
different meanings for this value, depending on if you provide a positive
or a negative integer.
A positive integer means "start consuming from this exact offset value".
A negative integer means "start consuming from the end, minus this value".
For easy configuration, these can be set using the following two options:
streamconfig.KafkaOffsetHead(i uint32)
streamconfig.KafkaOffsetTail(i uint32)
There are two important things to note here:
First, this configuration is inherently different from the `OffsetInitial`
property supported by Kafka. The initial property is defined as follows:
> Action to take when there is no initial offset in offset store or the
> desired offset is out of range
Meaning that this value will be used …
=> Add support for absolute (tailing) default offsets

streamconfig/option.go, streamconfig/option_test.go
The `streamconfig.KafkaGroupIDRandom()` option allows you to easily assign
a random group ID to the consumer every time you start that consumer.
This is useful for one-off consumers that aren't allowed to share consumer
group state with other consumers, or between runs.
This can be used in combination with `streamconfig.KafkaOffsetHead()` or
`streamconfig.KafkaOffsetTail()` to make sure the consumer starts reading
from that configured offset every time you start the consumer, instead of
picking up where it left off in the previous consumer group ID.
A concrete example would be if you want to always get the last message in
a specific topic. To do this, you would provide the following two options:
streamconfig.KafkaGroupIDRandom()
streamconfig.KafkaOffsetTail(1)
=> Add support for `KafkaGroupIDRandom` option

streamconfig/config_test.go, streamconfig/kafkaconfig/consumer.go, streamconfig/kafkaconfig/consumer_test.go, streamconfig/kafkaconfig/producer.go, streamconfig/kafkaconfig/producer_test.go, streamconfig/option.go, streamconfig/option_test.go
This is a convenience option to set `MaxInFlightRequests` to 1 for the
producer (NOT the consumer), to guarantee ordered message delivery.
This was set to 0 to guarantee delivery ordering, but with the
introduction of `MaxInFlightRequests` and the convenience option
`streamconfig.KafkaOrderedDelivery()`, this can now be set back
to rdkafka's default of 2 retries per delivery.
For more details on this, see these two links:
* https://git.io/vpgiV
* https://git.io/vpgDg
=> Increase delivery retries and add option to guarantee delivery ordering

streamclient/inmemclient/consumer.go, streamclient/inmemclient/consumer_test.go, streamclient/inmemclient/producer.go, streamclient/inmemclient/producer_test.go, streamclient/kafkaclient/consumer.go, streamclient/kafkaclient/consumer_test.go, streamclient/kafkaclient/producer.go, streamclient/kafkaclient/producer_test.go, streamclient/kafkaclient/testing_test.go, streamclient/standardstreamclient/consumer.go, streamclient/standardstreamclient/consumer_test.go, streamclient/standardstreamclient/producer.go, streamclient/standardstreamclient/producer_test.go, streamclient/testing_test.go, streamconfig/config.go, streamconfig/config_test.go, streamconfig/initializers.go, streamconfig/testing_test.go, streamutil/interrupt.go, streamutil/interrupt_test.go, streamutil/testutil/testing.go, streamutil/testutil/testing_test.go
If `ManualInterruptHandling` was set to `true`, no signals channel was
created, which caused a panic when closing a consumer or producer.
This fixes that.
=> Fix panic closing client with manual interrupts

streamclient/kafkaclient/eventhandlers.go, streamconfig/config_test.go, streamconfig/kafkaconfig/consumer.go, streamconfig/kafkaconfig/consumer_test.go, streamconfig/option.go, streamconfig/option_test.go
This is a follow-up to https://github.com/blendle/go-streamprocessor/pull/73.
---
Since offsets are zero-based, setting the default offset to 0 is a
valid use-case.
This change makes OffsetDefault a pointer to an int64 value, making it
possible to distinguish between a `0` offset, and an unset (`nil`)
offset.
The convenience options `KafkaOffsetHead` and `KafkaOffsetTail` still
work the same as before, accepting an int32 value.
=> Support zero-based default offset

Gopkg.lock, Gopkg.toml, streamconfig/option.go, streamconfig/option_test.go
This is a follow-up to https://github.com/blendle/go-streamprocessor/pull/74.
---
Before, `streamconfig.KafkaGroupIDRandom()` would generate a random
group ID based on a random int64 value. It required you to pass in a
seed value to make sure the returned ID was _actually_ random.
Now, no argument is required, and instead the group ID is now based on a
generated UUID V4 string.
There are several reasons for this change:
- the interface is easier (no more arguments required)
- it is in-line with how `kafkacat` handles random group IDs
- it increases the randomness, reducing group ID collisions
=> Swap KafkaGroupIDRandom from rand int64 to uuidV4

streamconfig/kafkaconfig/consumer_test.go, streamconfig/kafkaconfig/producer.go, streamconfig/kafkaconfig/producer_test.go
This was already set for the consumer, but not the producer.
=> Correctly set Kafka's default producer security protocol

streamconfig/kafkaconfig/consumer.go, streamconfig/kafkaconfig/consumer_test.go
To improve performance of fast processors, and improve equality when
consuming from multiple partitions.
=> Tweak consumer configuration

streamutil/usage.go
This was triggered by @niels-s trying to use one of the processors, using `--help` and expecting to see how the processor works.
While all processors have their own README, they don't (always) cover the exact usage/configuration of the consumers/producers.
This is an initial (pretty crappy) version. But I wanted to have _something_ for now.
See https://github.com/blendle/go-streamprocessor/issues/85 for future plans.
---
A processor would use this at the top of the `main` function as follows:
```golang
about := streamutil.About{
Name:      "Stream Processor: Hello World",
URI:       "https://my-link-to-docs",
Usage:     "Brief description about this processor.",
Config:    map[string]string{
"MY_CONFIG_ENV_VAR": "env var description here...",
"MY_OTHER_ENV_VAR": "another description …
```
=> Add initial support for printing processor usage

stream/common.go, stream/consumer.go, stream/producer.go, streamutil/error.go, streamutil/error_test.go
I came to the realization that the current error handling is flawed in a
sense that we use the provided Zap logger's `Fatal` method to log the
error.
This method then calls `os.Exit(1)`, see also: https://git.io/vhf3n.
The problem with this is that `os.Exit` does _not_ allow any deferred
functions to be executed, as it exits immediately, this unlike `panic`,
which _does_ allow the stack to complete before terminating.
But even if we switch to using `panic` instead, it would still not be
enough, because we could only handle a correct termination of the
_current_ consumer or producer, but if a processor uses multiple
consumers and/or producers, the others would still terminate without
properly cleaning up.
Cleaning up is especially important in the case of a Kafka client, since
it heavily …
=> Add convenience function to handle stream errors

streamlog/logger.go, streamlog/logger_test.go
This change adds the `streamlog` package. It currently exposes a single
function:
func Message(m stream.Message) zap.Field
You pass in a `stream.Message`, and a `zap.Field` is returned, that can
be directly passed into a Zap log entry:
logger.Info("My message details.", streamlog.Message(msg))
For simplicity and consistency, the field key cannot be changed. It
will be set to `streamMessage`. If you want to change this field, you
can implement your own marshaller.
=> Add helper function to marshal messages in Zap log entries

streamclient/consumer.go, streamclient/consumer_test.go, streamclient/producer.go, streamclient/producer_test.go, streamclient/type.go, streamconfig/consumer.go, streamconfig/consumer_test.go, streamconfig/producer.go, streamconfig/producer_test.go
closes https://github.com/blendle/go-streamprocessor/issues/84
---
Before, you could only use one type of consumer and producer at the
same time. You did this by setting the `STREAMCLIENT_CONSUMER` and
`STREAMCLIENT_PRODUCER` environment variable.
If you had multiple consumers in your application, all of them would
become of the type you set with `STREAMCLIENT_CONSUMER`.
After this commit, we use the defined consumer (and producer) names to
determine the environment variables used to set their types.
For example, if your (pseudo) code looks like this:
consumer, err := streamclient.NewConsumer()
consumer, err := streamclient.NewConsumer(streamconfig.Name("hello"))
producer, err := streamclient.NewProducer()
You can now set the type for these consumers and producer independently,
as …
=> Allow using multiple streamclient types concurrently

streamclient/producer.go, streamclient/producer_test.go
Before, `PRODUCER_CLIENT_TYPE=inmem` would override `DRY_RUN=1`. This
can cause dangerous situations where you expect adding `DRY_RUN` to
"just work", and no data to be produced to any production-like clients.
Now, `DRY_RUN` always overrides any other preferences, meaning all
producers in the application will produce their data to `stdout`.
=> Make sure DRY_RUN is always honored for producers

streamclient/standardstreamclient/consumer.go, streamclient/standardstreamclient/consumer_test.go
This makes the client compatible/usable in stream processors that act
on message timestamps.
=> Set standardstream's consumed messages timestamp to "now"

README.md, streamconfig/inmemconfig/consumer.go, streamconfig/option.go
This will need more fine-tuning, but we'll add/tweak anything that's missing/wrong once more people use the documentation.
---
This package contains shared logic for Go-based stream processors.
* [Description](#description)
* [Messages](#messages)
* [Stream Clients](#stream-clients)
* [Kafka](#kafka)
* [Inmem](#inmem)
* [Standardstream](#standardstream)
* [Shared Interface](#shared-interface)
* [Usage](#usage)
* [Initialization](#initialization)
* [Consuming](#consuming)
* [Producing](#producing)
* [Error Handling](#error-handling)
* [Multiple Clients](#multiple-clients)
* [Stream Options](#stream-options)
The `go-streamprocessor` package includes utilities to work with streams of data
from different sources. You can consume messages, have your business logic use
or manipulate the …
=> Add initial library description to README

streamclient/kafkaclient/eventhandlers.go, streamclient/kafkaclient/eventhandlers_test.go, streamconfig/kafkaconfig/consumer.go, streamconfig/kafkaconfig/consumer_test.go, streamconfig/kafkaconfig/producer.go, streamconfig/kafkaconfig/producer_test.go, streamconfig/option.go, streamconfig/option_test.go
Instead of exposing all errors that are returned by the Kafka brokers,
now only any non-transient errors are returned. This is in accordance
with the rdkafka documentation:
> These errors are normally just informational since the
> client will try its best to automatically recover (eventually)
If you want, you can still expose _all_ errors, by using the option:
streamconfig.KafkaHandleTransientErrors()
=> Ignore transient errors when applicable

stream/consumer.go, stream/consumermock.go, streamclient/inmemclient/consumer.go, streamclient/inmemclient/consumer_test.go, streamclient/kafkaclient/consumer.go, streamclient/kafkaclient/consumer_test.go, streamclient/kafkaclient/testing.go, streamclient/standardstreamclient/consumer.go, streamclient/standardstreamclient/consumer_test.go
This allows for processors to determine their mode of operation, based on the messages still waiting to be consumed.
For example, if a processor continuously consumes messages, and periodically produces messages based on the previously consumed messages, it might be desired to have the producer only trigger if the backlog of the consumer is small enough. This allows for dynamically catching up with a larger backlog during peak-hours.
The method signature is straightforward:
```golang
Backlog() (int, error)
```
Stream client implementations that have no concept of message persistence or consumer identity, always return `0`. The error will be non-nil if any error occurred while fetching the required data.
=>  Add `Backlog` method signature to Consumer interface

streamutil/error.go, streamutil/error_test.go
Before, if you listened for any errors using streamutil.Errors, if the
errors channel was closed, a nil error was returned by the function.
This usually happened if you close a consumer or producer, but are still
listening for errors. Since the consumer or producer will close its
errors channel, you would receive a nil value.
This was error prone, as you had to explicitly check for non-nil errors
before acting on the error.
Now, an explicit nil error is delivered as expected, but a nil error due
to channel closure is ignored.
=> Don't return nil error when the error channel closes

.travis.yml, Gopkg.lock, script/bootstrap, streamclient/kafkaclient/eventhandlers_test.go, streamclient/kafkaclient/producer_test.go, streamclient/kafkaclient/testing.go, streamconfig/consumer_test.go, streamconfig/global.go, streamconfig/producer_test.go, streamconfig/testing_test.go, streamutil/testutil/testing.go, streamutil/testutil/testing_test.go
See: https://github.com/uber-go/zap/pull/518
=> Deprecate test logger in favour of new Zap test logger

streamconfig/kafkaconfig/producer.go, streamconfig/kafkaconfig/producer_test.go, streamconfig/option.go, streamconfig/option_test.go
I've seen situations where our cluster is returning some errors, and doesn't recover immediately, but will after a few seconds. By default, the retry logic retries after 100ms, which is too short for the cluster to recover.
With this change:
* a processor will retry 5 times
* there is 15 seconds between each retry, giving the broker a total of 1 minute and 15 seconds before the processor exits with an error
* the processor now waits for an Ack from all brokers, not just the leader, before marking a publish action as a success.
All of these values can be configured, but the default favours stability and correctness, over speed. In general though, I don't hink these changes will cause a big change in performance, because the producer already batches messages (10.000 by default) before …
=> Tweak numbers related to retries, and message delivery guarantee

.travis.yml, Gopkg.lock, Gopkg.toml, streamclient/kafkaclient/producer.go, streamclient/kafkaclient/testing.go, streamclient/kafkaclient/testing_test.go, streamclient/testing.go, streamconfig/consumer_test.go, streamconfig/kafkaconfig/consumer.go, streamconfig/kafkaconfig/consumer_test.go, streamconfig/kafkaconfig/producer.go, streamconfig/option.go, streamconfig/option_test.go
A couple of notes:
- we kept the current Golang version dependency for now
- we didn't migrate to `go mod` yet, there's no need for now
- we had to increase some test timeouts due to more random failures, either because Travis hardware changed since we worked on this project, or because the 1.0.0 upgrade made it a bit harder to do the kind of testing we're doing (fast creation of topics, inserting and fetching data, and then deleting the topics again).
- we used the upgrade guide of both [librdkafka](https://github.com/edenhill/librdkafka/releases/tag/v1.0.0) and [confluent-kafka-go](https://github.com/confluentinc/confluent-kafka-go/releases/tag/v1.0.0)
- we didn't add the new idempotent producer functionality yet, it would help us a lot, but that'll have to wait for another time.
I'll …
=> Upgrade librdkafka to 1.0.0

streamconfig/kafkaconfig/producer.go, streamconfig/kafkaconfig/producer_test.go
1ms is the librdkafka default, but it's tuned for lowest possible latency. After 1000ms, the increase in throughput is (according to the documentation) negligible, so let's set this to 500ms for a nice middle ground, and individual applications can tweak as needed.
=> better default for MaxQueueBufferDuration

streamconfig/kafkaconfig/producer.go, streamconfig/kafkaconfig/producer_test.go
It's faster than Snappy, in most circumstances.
=> better default for CompressionCodec

streamclient/kafkaclient/consumer.go, streamclient/kafkaclient/producer.go
This will help debugging when a processor is suddenly closed.
=> add log message with stacktrace on close

script/bootstrap
This allows the master build to pass again.
=> Update shellcheck url
